// This file was autogenerated by depswriter.py
// Please do not edit.
goog.addDependency('../browser/base.js', ['goog'], []);
goog.addDependency('../remora.js', ['remora'], ['remora.AST2JS', 'remora.ASTTransforms', 'remora.evaler', 'remora.log', 'remora.parser', 'remora.utils']);
goog.addDependency('../remora/AST2JS.js', ['remora.AST2JS'], ['remora.ASTWalker']);
goog.addDependency('../remora/ASTTransforms.js', ['remora.ASTTransforms'], ['remora.ASTWalker']);
goog.addDependency('../remora/ASTWalker.js', ['remora.ASTWalker'], []);
goog.addDependency('../remora/evaler.js', ['remora.evaler'], []);
goog.addDependency('../remora/log.js', ['remora.log'], []);
goog.addDependency('../remora/parser.js', ['remora.parser'], []);
goog.addDependency('../remora/utils.js', ['remora.utils'], []);
